<!doctype html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Task Master · Your workspace</title>
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Raleway:wght@400;500;600;700;800&display=swap" rel="stylesheet">
    <style>
        :root { --ink:#172033; --muted:#72809a; --canvas:#f5f7fb; --surface:#fff; --line:#e6eaf1; --primary:#5856d6; --primary-dark:#4543bc; --soft:#eeefff; --danger:#d84d63; }
        [data-theme="dark"] { --ink:#edf0fb; --muted:#9ba7c1; --canvas:#111522; --surface:#1a2030; --line:#2a3348; --primary:#8583f5; --primary-dark:#9b99ff; --soft:#252b4b; --danger:#f0788c; }
        * { box-sizing:border-box; } body { margin:0; min-height:100vh; font-family:"Raleway", -apple-system, BlinkMacSystemFont, "Segoe UI", sans-serif; color:var(--ink); background:radial-gradient(circle at 82% -15%, #e5e9ff 0, transparent 31rem),var(--canvas); font-size:15px; line-height:1.55; } button,input,textarea,select { font-family:inherit; }
        nav { height:72px; padding:0 max(28px, calc((100% - 1120px)/2)); display:flex; justify-content:space-between; align-items:center; background:#ffffffd9; border-bottom:1px solid #e8ebf2; backdrop-filter:blur(16px); animation:slideDown .45s ease both; }
        .nav-login { padding:8px 10px; color:#4b5870!important; border-radius:8px; font-weight:650; transition:color .18s,background .18s; } .nav-login:hover { color:var(--primary)!important; background:#f2f2ff; } .nav-register { position:relative; overflow:hidden; padding:9px 14px; color:#fff!important; background:linear-gradient(135deg,#6967e7,#504dcc); border-radius:9px; box-shadow:0 6px 15px #5d5adc2e; font-weight:700; transition:transform .18s,box-shadow .18s; } .nav-register::after { position:absolute; inset:0; content:""; background:linear-gradient(110deg,transparent 25%,#ffffff50 48%,transparent 70%); transform:translateX(-120%); transition:transform .5s ease; } .nav-register:hover { transform:translateY(-2px); box-shadow:0 9px 19px #5d5adc42; } .nav-register:hover::after { transform:translateX(120%); } .nav-register:active { transform:translateY(0) scale(.96); }
        .theme-toggle { display:grid; width:34px; height:34px; place-items:center; border:1px solid #e2e6ef; border-radius:9px; color:#596781; background:#fff; cursor:pointer; transition:transform .18s,background .18s,color .18s; } .theme-toggle:hover { color:var(--primary); background:#f2f2ff; transform:rotate(12deg); } .theme-toggle:active { transform:rotate(0) scale(.9); } .theme-toggle svg { width:17px; height:17px; }
        nav a { color:var(--ink); text-decoration:none; } .brand { display:flex; align-items:center; gap:10px; font-weight:750; letter-spacing:-.04em; font-size:1.12rem; } .brand::before { content:"✓"; display:grid; width:28px; height:28px; place-items:center; color:#fff; background:linear-gradient(135deg,#7774f4,#4d46c8); border-radius:9px; font-size:.85rem; box-shadow:0 5px 12px #5d5adc38; } .nav-links { display:flex; gap:12px; align-items:center; color:var(--muted); font-size:.9rem; }
        .container { max-width:1120px; margin:48px auto; padding:0 28px; } h1,h2 { letter-spacing:-.04em; } h1 { margin:0; font-size:2rem; line-height:1.15; } h2 { margin:0; font-size:1.06rem; } h2 a { color:var(--ink); text-decoration:none; } h2 a:hover { color:var(--primary); } p { margin:8px 0; }
        .card { background:var(--surface); border:1px solid var(--line); border-radius:16px; padding:24px; margin-bottom:14px; box-shadow:0 8px 28px rgba(27,39,78,.035); transition:transform .22s ease,box-shadow .22s ease,border-color .22s ease; } article.card:hover { transform:translateY(-3px); border-color:#d7daf9; box-shadow:0 15px 34px rgba(27,39,78,.075); }
        .page-head { display:flex; justify-content:space-between; align-items:center; gap:20px; margin-bottom:28px; } .page-head .meta { margin-top:8px; } .btn { position:relative; display:inline-flex; align-items:center; justify-content:center; overflow:hidden; border:1px solid transparent; border-radius:9px; padding:10px 15px; background:var(--primary); color:#fff; cursor:pointer; text-decoration:none; font-family:inherit; font-size:.88rem; font-weight:600; transition:transform .18s ease,box-shadow .18s ease,background .18s ease; } .btn::after { position:absolute; width:110%; height:160%; content:""; background:#ffffff2e; border-radius:50%; transform:scale(0); transition:transform .35s ease; } .btn:hover { background:var(--primary-dark); transform:translateY(-2px); box-shadow:0 9px 19px #5856d62b; } .btn:active { transform:translateY(0) scale(.97); box-shadow:none; } .btn:active::after { transform:scale(1); transition:transform 0s; }
        .btn.secondary { background:#fff; color:#536078; border-color:#dfe4ed; } .btn.secondary:hover { background:#f7f8fb; box-shadow:none; } .btn.danger { background:#fff4f5; color:#c43f55; border-color:#ffdce1; } .btn.danger:hover { background:#ffe9ec; box-shadow:none; } .btn.small { padding:7px 11px; border-radius:8px; font-size:.8rem; } .inline { display:inline; }
        label { display:block; margin:20px 0 7px; color:#34415a; font-size:.84rem; font-weight:650; } input,textarea,select { width:100%; padding:11px 12px; color:var(--ink); background:#fff; border:1px solid #dfe4ed; border-radius:9px; font:inherit; outline:none; transition:border-color .15s,box-shadow .15s; } input:focus,textarea:focus,select:focus { border-color:#8987eb; box-shadow:0 0 0 4px #5856d61a; } textarea { min-height:110px; resize:vertical; }
        .alert { padding:13px 16px; border-radius:11px; margin-bottom:18px; font-size:.9rem; animation:noticeIn .35s ease both; } .success { color:#16704b; background:#ecfbf4; border:1px solid #cef3df; } .error { color:#b5394f; background:#fff2f4; border:1px solid #ffdade; }
        .errors { margin:0; padding-left:20px; } .meta { color:var(--muted); font-size:.9rem; } .meta a { color:#6975c9; text-decoration:none; transition:color .18s; } .meta a:hover { color:var(--primary); } .actions { display:flex; flex-wrap:wrap; gap:8px; margin-top:18px; } .task { display:flex; justify-content:space-between; align-items:flex-start; gap:24px; transition:background .18s,transform .18s; } .task:hover { transform:translateX(3px); } .task p { color:#66748b; font-size:.92rem; }
        .badge { padding:5px 10px; border-radius:999px; background:#f0f1ff; color:#5754bc; white-space:nowrap; font-size:.76rem; font-weight:650; transition:transform .18s ease; } .task:hover .badge { transform:scale(1.05); } .badge.status-to-do { color:#68758a; background:#eff2f6; } .badge.status-in-progress { color:#6654b5; background:#f0edff; } .badge.status-done { color:#1d8259; background:#e9f9f0; } .empty { text-align:center; color:var(--muted); padding:38px; } .filter { display:flex; gap:10px; align-items:end; margin-bottom:18px; padding-bottom:18px; border-bottom:1px solid var(--line); } .filter label { margin-top:0; } .filter select { max-width:220px; cursor:pointer; }
        .auth-shell { max-width:960px; min-height:560px; display:grid; grid-template-columns:1.05fr .95fr; overflow:hidden; margin:36px auto; background:var(--surface); border:1px solid var(--line); border-radius:22px; box-shadow:0 24px 65px rgba(39,44,100,.12); } .auth-intro { position:relative; display:flex; flex-direction:column; justify-content:space-between; padding:48px; overflow:hidden; color:#fff; background:linear-gradient(145deg,#403cab 0%,#5856d6 52%,#7a78ee 100%); } .auth-intro::after { content:""; position:absolute; width:330px; height:330px; right:-120px; bottom:-120px; border:54px solid #ffffff18; border-radius:50%; } .eyebrow { margin:0 0 16px; color:#d9d9ff; font-size:.76rem; font-weight:700; letter-spacing:.12em; text-transform:uppercase; } .auth-intro h1 { max-width:370px; font-size:2.5rem; } .auth-intro p { max-width:350px; color:#ececff; } .feature-list { display:grid; gap:12px; position:relative; z-index:1; margin-top:26px; } .feature-list span { display:flex; align-items:center; gap:9px; color:#f7f7ff; font-size:.88rem; } .feature-list span::before { content:""; width:7px; height:7px; border-radius:50%; background:#b7d5ff; box-shadow:0 0 0 4px #ffffff18; } .auth-form { display:flex; flex-direction:column; justify-content:center; padding:48px; background:var(--surface); } .auth-form h2 { font-size:1.6rem; } .auth-form .meta { margin-top:6px; } .auth-form form { margin-top:12px; } .auth-form .btn { width:100%; margin-top:8px; } .auth-link { display:block; margin-top:20px; color:var(--muted); font-size:.88rem; text-align:center; } .auth-link a { color:var(--primary); font-weight:650; text-decoration:none; }
        .password-field { position:relative; } .password-field input { padding-right:52px; } .password-toggle { position:absolute; right:8px; top:50%; display:grid; width:32px; height:32px; place-items:center; border:0; border-radius:8px; transform:translateY(-50%); padding:5px; color:#5c63a9; background:transparent; cursor:pointer; transition:color .18s,background .18s,transform .18s; } .password-toggle:hover { color:var(--primary); background:#f0f0ff; } .password-toggle:active { transform:translateY(-50%) scale(.86); } .password-toggle svg { width:18px; height:18px; transition:transform .24s ease,opacity .18s ease; } .password-toggle.is-visible svg { transform:rotate(-12deg) scale(1.12); } .password-hint { margin:7px 0 0; color:var(--muted); font-size:.78rem; }
        [data-theme="dark"] body { background:radial-gradient(circle at 82% -15%, #2c2c5c 0, transparent 31rem),var(--canvas); } [data-theme="dark"] nav { background:#171c2bd9; border-color:var(--line); } [data-theme="dark"] nav a { color:var(--ink); } [data-theme="dark"] .card,[data-theme="dark"] .auth-shell { box-shadow:0 8px 28px #02040b55; } [data-theme="dark"] .auth-form { background:linear-gradient(145deg,#1b2233,#171c2a); } [data-theme="dark"] .btn.secondary,[data-theme="dark"] .theme-toggle { color:#c2cbe1; background:#20283a; border-color:#364158; } [data-theme="dark"] .btn.secondary:hover,[data-theme="dark"] .theme-toggle:hover { background:#293249; } [data-theme="dark"] input,[data-theme="dark"] textarea,[data-theme="dark"] select { color:var(--ink); background:#151b29; border-color:#364158; } [data-theme="dark"] .nav-login { color:#c2cbe1!important; } [data-theme="dark"] .nav-login:hover,[data-theme="dark"] .password-toggle:hover { background:#272b4b; } [data-theme="dark"] .task p { color:#a6b0c5; }
        main > * { animation:fadeUp .42s ease both; } main > *:nth-child(2) { animation-delay:.05s; } main > *:nth-child(3) { animation-delay:.1s; } @keyframes fadeUp { from { opacity:0; transform:translateY(12px); } to { opacity:1; transform:translateY(0); } } @keyframes slideDown { from { opacity:0; transform:translateY(-10px); } to { opacity:1; transform:translateY(0); } } @keyframes noticeIn { from { opacity:0; transform:scale(.97); } to { opacity:1; transform:scale(1); } } @media (prefers-reduced-motion:reduce) { *,*::before,*::after { scroll-behavior:auto!important; animation-duration:.01ms!important; animation-iteration-count:1!important; transition-duration:.01ms!important; } } @media (max-width:760px) { .auth-shell { grid-template-columns:1fr; margin:10px auto; } .auth-intro { min-height:260px; padding:34px; } .auth-intro h1 { font-size:2rem; } .auth-form { padding:34px; } } @media (max-width:600px) { nav { height:auto; padding-block:14px; } .page-head,.task,nav { align-items:flex-start; flex-direction:column; } .container { margin:30px auto; padding:0 18px; } h1 { font-size:1.7rem; } .card { padding:19px; } }
    </style>
</head>
<body>
<nav>
    <a class="brand" href="{{ auth()->check() ? route('projects.index') : route('login') }}">Task Master</a>
    <div class="nav-links">
        <button id="themeToggle" class="theme-toggle" type="button" aria-label="Switch color theme" title="Switch color theme"><svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><circle cx="12" cy="12" r="4"/><path d="M12 2v2M12 20v2M4.93 4.93l1.41 1.41M17.66 17.66l1.41 1.41M2 12h2M20 12h2M4.93 19.07l1.41-1.41M17.66 6.34l1.41-1.41"/></svg></button>
        @auth
            <span>{{ auth()->user()->name }}</span>
            <form class="inline" method="POST" action="{{ route('logout') }}">@csrf <button class="btn small secondary">Logout</button></form>
        @endauth
        @guest
            <a class="nav-login" href="{{ route('login') }}">Login</a><a class="nav-register" href="{{ route('register') }}">Create account</a>
        @endguest
    </div>
</nav>
<main class="container">
    @if(session('success')) <div class="alert success">{{ session('success') }}</div> @endif
    @if(session('error')) <div class="alert error">{{ session('error') }}</div> @endif
    @if($errors->any()) <div class="alert error"><ul class="errors">@foreach($errors->all() as $error)<li>{{ $error }}</li>@endforeach</ul></div> @endif
    @yield('content')
</main>
<script>const themeKey='task-master-theme',toggle=document.getElementById('themeToggle'),sun='<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><circle cx="12" cy="12" r="4"/><path d="M12 2v2M12 20v2M4.93 4.93l1.41 1.41M17.66 17.66l1.41 1.41M2 12h2M20 12h2M4.93 19.07l1.41-1.41M17.66 6.34l1.41-1.41"/></svg>',moon='<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><path d="M21 12.8A9 9 0 1 1 11.2 3 7 7 0 0 0 21 12.8Z"/></svg>';const applyTheme=theme=>{document.documentElement.dataset.theme=theme;toggle.innerHTML=theme==='dark'?sun:moon;toggle.title=theme==='dark'?'Use light theme':'Use dark theme';};const savedTheme=localStorage.getItem(themeKey),initialTheme=savedTheme||(matchMedia('(prefers-color-scheme: dark)').matches?'dark':'light');applyTheme(initialTheme);toggle.addEventListener('click',()=>{const next=document.documentElement.dataset.theme==='dark'?'light':'dark';localStorage.setItem(themeKey,next);applyTheme(next);});</script>
</body>
</html>
